Issue 63
isaacharrisholt/quiffen pull request #74
Opened 2023-10-17 13:07 UTC by WolfgangFahl

fixes #63

2023-10-17 13:09 UTC, WolfgangFahl commented
The test might have to reset the split_overshoot after being done

2023-10-18 18:25 UTC, isaacharrisholt requested changes
When introducing new functionality like this, it's generally good GitHub etiquette to come to a solution in an issue before implementing the code. Perhaps it would be good to use issue #63 for that purpose here.

2023-10-18 18:25 UTC, isaacharrisholt commented on tests/test_transaction.py
> +def test_split_overshoot_issue63():
As you might see with other tests, the issue is typically referenced in the docstring, not the function name

2023-10-18 18:25 UTC, isaacharrisholt commented on quiffen/core/transaction.py
> +
I'm not sure I'm a fan of storing config on a class like this. Also, if this is intended to be user-editable, then perhaps there's a better way of approaching this than a global config object.

2023-10-19 08:00 UTC, WolfgangFahl commented
Still this is an improvement and doesn't break anything. I don't see why this shouldn't be accepted ASAP.

2023-10-23 17:19 UTC, isaacharrisholt commented
> Still this is an improvement and doesn't break anything. I don't see why this shouldn't be accepted ASAP.

Perhaps, but I also have to consider the longer-term view for this project. I'm ultimately going to be the one maintaining this, and if I wanted to change it, which I likely would, I'd have to release a new major version of Quiffen. This needs more discussion.

2023-11-04 11:04 UTC, isaacharrisholt commented
Closing due to inactivity. Feel free to open a discussion thread to discuss implementation.

2023-11-04 11:04 UTC, closed without merging